spring:
  config:
    activate:
      on-profile: common
  data:
    mongodb:
      url: mongodb+srv://kyuwon:tlarb3011@cluster0.nclsjib.mongodb.net/rememberMe?retryWrites=true&w=majority&appName=Cluster0
  jwt:
    secret: rjsrnreogkrrytlarbdnjsdlqslekrkatkgkqslekaaavvvvvvrlrlrldjfuqwl
gpt:
  model: gpt-3.5-turbo
  api:
    url: https://api.openai.com/v1/chat/completions
    key: ${API_KEY}